export default {
  logo: require('./lightModeLogo.png'),
  openEye: require('./openEye.png'),
  closedEye: require('./closedEye.png'),
  playButton: require('./playButton.png'),
  homeTabIcon: require('./homeTabIcon.png'),
  editIcon: require('./editIcon.png'),
  menuIcon: require('./menuIcon.png'),
  backIcon: require('./backIcon.png'),
  cameraIcon: require('./cameraIcon.png'),
  galleryIcon: require('./galleryIcon.png'),
  notificationIcon: require('./notificationIcon.png'),
  addImageIcon: require('./addImageIcon.png'),
  profileImage: require('./profileImage.png'),
  profileTabIcon: require('./profileTabIcon.png'),
  videoTabIcon: require('./videoTabIcon.png'),
  createTabIcon: require('./createTabIcon.png'),
  creatorBitmoji: require('./creatorBitmoji.png'),
  upArrow: require('./upArrow.png'),
  downArrow: require('./downArrow.png'),
  crossIcon: require('./crossIcon.png'),
  drawerProfile: require('./drawerProfile.png'),
  selectIcon: require('./selectIcon.png'),
};
