export default {
  HomeScreen: 'HomeScreen',
  CreateScreen: 'CreateScreen',
  Dashboard: 'Dashboard',
  DrawerNavigation: 'DrawerNavigation',
  SplashScreen: 'SplashScreen',
  ProfileScreen: 'ProfileScreen',
  Signup: 'SignupScreen',
  Login: 'LoginScreen',
  VideoScreen: 'VideoScreen',
  VideoDisplayScreen: 'VideoDisplayScreen',
  WebViewScreen: 'WebViewScreen',
  Notification: 'Notification',
  UserDetailsScreen: 'UserDetailsScreen',
};
