export const strings: Record<string, string> = {
  clear: 'Clear',
  noSearch: 'No Result found for this search',
  noData: 'No Data available',
  version: 'Version 1.0.0',
  UserDetails: 'User Details',
  dark: 'Dark',
  light: 'Light',
  sysDefault: 'System Default',
  noResults: 'No match found for this search',
  noNotification: 'You have no new notifications',
  notification: 'Notifications',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  changePassword: 'Change Password',
  passwordUpdated: 'Password Updated',
  settings: 'Settings',
  changeTheme: 'Change Theme',
  termsAndConditions: 'Terms and Conditions',
  privacyPolicy: 'Privacy Policy',
  videoDetails: 'Video Details',
  views: 'views',
  subscribers: 'Subscribers',
  hello: 'Hello',
  stream: 'Stream',
  editDetails: 'Edit Details',
  profile: 'Profile',
  home: 'Home',
  create: 'Create',
  loginHeader: 'Login',
  signupHeader: 'Signup',
  email: 'Email',
  password: 'Password',
  haveAccount: 'Have an Account? ',
  noAccount: "Don't have an Account? ",
  signUp: 'Sign Up',
  firstName: 'First name',
  lastName: 'Last name',
  phone: 'Phone number',
  confirmPassword: 'Confirm Password',
  tagLine: 'Your go to video streaming partner!',
  createScreen: 'CreateScreen',
  homeScreen: 'HomeScreen',
  profileScreen: 'Profile Screen',
  loginMessage: 'This email already exists so please login',
  signupMessage: "This email doesn't exist. Please signup to create an account",
  permissionBlocked:
    'This feature has been denied to access this feature change the permission from settings',
  permissionUnavailable:
    'This feature is not available (on this device / in this context)',
  emailExists: 'This email already exists',
  permissionLimited:
    'The permission is granted but with limitations. To use all the features please change the permission from settings',
  video: 'Video',
  videoDescription:
    'Well, YouTube states that your video’s metadata (including your description) plays a role in the Suggested Video Algorithm. In other words, if keywords in your description matches the keywords in another video’s description, there’s a good chance YouTube will promote you as a Suggested Video',
  userBio:
    "I love selling brands. So here's few quick things about me and my work. In, out, nobody gets hurt.I'm a digital junkie with 23,000 Twitter followers. I love every freakin' thing about the web.I got my job in advertising in an unusual way. I won a national writing contest called' Write If You Want Work'I don't like to advertise this fact, but I'd do this job for free. It's my passion. Also, aside from advertising, I'm completely unemployable.",
  about: 'About',
};
export const buttons: Record<string, string> = {
  logout: 'Logout',
  login: 'Log in',
  signUp: 'Sign up',
  addUser: 'Add User',
  editUser: 'Edit User',
  changePassword: 'Update',
};
export const errorMessages: Record<string, string> = {
  short: 'Too Short!',
  long: 'Too Long!',
  empty: "This field can't be empty",
  invalidEmail: 'Invalid email',
  invalidPassword:
    'Must contain minimum 8 characters, at least one uppercase letter, one lowercase, one special character, one digit',
  invalidName: "Name can't have numbers, spaces or special characters",
  confirmPassword: 'Confirm Password should be same as Password',
  invalidMobile: 'Mobile number should be of exactly 10 digits',
  incorrectMobileNo: 'Mobile number can have only Digits',
  incorrectPassowrd: 'Incorrect password. Try again',
  samePassword:
    "New password can't be same as old Password. Try something else!",
  incorrectOldPassowrd: 'Old password is incorrect. Try again',
  error: 'Something went wrong. Please Try Again',
};
